### ISSUE TITLE
Enable SSLSessionCache for better performance

### ISSUE THREAD

**Issue by EvonX** [ManageIQ/container-httpd#39]
Hi,

It seems centos/httpd:latest doesn't set `SSLSessionCache`. But the [official document](https://httpd.apache.org/docs/current/mod/mod_ssl.html#SSLSessionCache) states no cache hurt performance:

> none
This disables the global/inter-process Session Cache. This will incur a noticeable speed penalty and may cause problems if using certain browsers, particularly if client certificates are enabled. This setting is not recommended.

Would enabling this a necessary and a quick way to improve performance?

Best,
-CC

**Comment by carbonin** [comment]
I think your ssl configuration would depend on your application config so it's not something we would want to specify in the base image.

For example, our primary use case for this image is to deploy it in OpenShift where we do TLS termination on the route rather than this container. So our [application configuration](https://github.com/ManageIQ/manageiq-pods/blob/4d6f63cdcf821a38e40f0d3756502647084dc78e/templates/miq-template.yaml#L151) doesn't utilize modssl at all.
